package com.fs.pcmens2.deploy.core;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;

public class ChecksumVerifier {


public void listChecksums(Path releaseDir) {
        Path file = releaseDir.resolve("checksums.sha256");
        if (Files.exists(file)) {
            try (BufferedReader br = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
                String line;
                System.out.println("Cheksums de la version en " + releaseDir + ":");
                while ((line = br.readLine()) != null) {
                    System.out.println(line);
                }
                System.out.println("---");
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }else{
            generateChecksums(releaseDir);
            listChecksums(releaseDir);
        }
    }

public void generateChecksums(Path releaseDir) {
        if (!Files.isDirectory(releaseDir)) throw new IllegalArgumentException("No existe directorio: " + releaseDir);
        Path out = releaseDir.resolve("checksums.sha256");
        try {
            List<Path> files;
            try (java.util.stream.Stream<Path> stream = Files.walk(releaseDir)) {
                files = stream.filter(Files::isRegularFile)
                              .filter(p -> !p.equals(out))
                              .map(releaseDir::relativize)
                              .sorted()
                              .toList();
            }
            try (var bw = Files.newBufferedWriter(out, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
                bw.write("# checksums generated by ChecksumVerifier");
                bw.newLine();
                for (Path rel : files) {
                    Path abs = releaseDir.resolve(rel);
                    String sum = sha256(abs);
                    String pathStr = rel.toString().replace('\\','/');
                    bw.write(sum + "  " + pathStr);
                    bw.newLine();
                }
            }
        } catch (IOException e) { throw new RuntimeException(e); }
    }
    private String sha256(Path file) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            try (InputStream is = Files.newInputStream(file)) {
                is.transferTo(new java.io.OutputStream() {
                    @Override public void write(int b) { md.update((byte)b); }
                    @Override public void write(byte[] b, int off, int len) { md.update(b, off, len); }
                });
            }
            byte[] bytes = md.digest();
            StringBuilder sb = new StringBuilder();
            for (byte b : bytes) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (Exception e) { throw new RuntimeException(e); }
    }
}

